  redis:
    # Warning: Redis changed to a proprietary license with v7.4 and later.
    # @see https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.3
    entrypoint:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
      - --loglevel notice

